name: Test setup-yak action

on: push

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use local action
        id: yak
        uses: ./
        with:
          token: "my-fake-token"
      - run: yak -h
      - run: $env:YAK_TOKEN
      - run: echo "${{ steps.yak.version }}"
