name: Test setup-yak action

on: push

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use local action
        uses: ./
        with:
          version: 0.10.0
      - run: yak -h
