name: Test setup-yak action

on: push

jobs:
  test:
    runs-on: windows-latest
    name: Test setup-yak action
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use local action
        id: yak
        uses: ./ # The root of this repo where action.yml lives
      - run: yak -h
      - name: "Test if $YAK_TOKEN is set"
        shell: "bash"
        run: |
          if [[ -z "${YAK_TOKEN}" ]]; then
            exit 1
          else
            exit 0
          fi
      - name: "Test if version output is set"
        shell: "bash"
        run: |
          if [[ -z "${{ steps.yak.outputs.version }}" ]]; then
            exit 1
          else
            exit 0
          fi
