name: Test setup-yak action

on: push

jobs:
  test:
    runs-on: windows-latest
    name: Test setup-yak action
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run pack # Ensure we're testing on the latest build
      - name: Use local action
        id: yak
        uses: ./ # The root of this repo where action.yml lives
        with:
          token: "my-fake-token"
      - run: yak -h
      - name: "Test if $YAK_TOKEN is set"
        shell: "bash"
        run: |
          if [[ -z "${YAK_TOKEN}" ]]; then
            exit 1
          else
            exit 0
          fi
      - name: "Test if version output is set"
        shell: "bash"
        run: |
          if [[ -z "${{ steps.yak.outputs.version }}" ]]; then
            exit 1
          else
            exit 0
          fi
      - name: Fail if git history is dirty
        run: |
          if [[ -z "$(git status --porcelain)" ]];
          then
            exit 0
          else
            exit 1
          fi
